### ISSUE TITLE
Could not find artifact com.dylibso.chicory:aot-maven-plugin-experimental:jar:999-SNAPSHOT

### ISSUE THREAD

**Issue by mkarg** [dylibso/chicory#704] opened 2024-12-12 09:07 UTC
It seems the `POM.xml` file is incomplete or buggy, as `mvn validate` leads to
```
[ERROR] Plugin com.dylibso.chicory:aot-maven-plugin-experimental:999-SNAPSHOT or one of its dependencies could not be resolved:
[ERROR]         Could not find artifact com.dylibso.chicory:aot-maven-plugin-experimental:jar:999-SNAPSHOT
```

**Comment by evacchi** [comment] 2024-12-12 09:59
IIRC with all the codegen and maven plugins happening, there is no way around `mvn install` at the moment

**Comment by andreaTP** [comment] 2024-12-12 13:33
@evacchi analysis is correct, we are using Maven Plugins defined in the build, and the relevant commands are reflected in the [developer documentation](https://github.com/dylibso/chicory/blob/main/CONTRIBUTING.md#building-the-runtime).

So, you always need to run at least once `mvn install`(or `mvn -Dquickly` depending on the case) before being able to move to the next command.

Any blocker/further issue caused by this setup?

**Comment by andreaTP** [comment] 2024-12-17 09:57
Closing as this is the expected behavior.

If there is any security/other concerns, feel free to re-open or open a new one.

**Closed by andreaTP** 2024-12-17 09:57 UTC
