### ISSUE TITLE
java.nio.file.NoSuchFileException: ../wasi-testsuite/tests/c/testsuite/fs-tests.dir

### ISSUE THREAD

**Issue by mkarg** [dylibso/chicory#705] opened 2024-12-12 12:41 UTC
```mvn install``` executed with latest head of `main` branch produces the follwing error:
```[ERROR] Tests run: 12, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 5.767 s <<< FAILURE! -- in com.dylibso.chicory.wasi.WasiPreview1Test
[ERROR] com.dylibso.chicory.wasi.WasiPreview1Test.wasiPositionedWriteWithAppendShouldFail -- Time elapsed: 0.073 s <<< ERROR!
java.nio.file.NoSuchFileException: ../wasi-testsuite/tests/c/testsuite/fs-tests.dir
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
        at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
        at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
        at java.base/java.nio.file.Files.readAttributes(Files.java:1764)
        at java.base/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:219)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:276)
        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2717)
        at java.base/java.nio.file.Files.walkFileTree(Files.java:2797)
        at com.dylibso.chicory.wasi.Files.copyDirectory(Files.java:26)
        at com.dylibso.chicory.wasi.WasiPreview1Test.wasiPositionedWriteWithAppendShouldFail(WasiPreview1Test.java:247)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   WasiPreview1Test.wasiPositionedWriteWithAppendShouldFail:247 » NoSuchFile ../wasi-testsuite/tests/c/testsuite/fs-tests.dir
[INFO] 
[ERROR] Tests run: 12, Failures: 0, Errors: 1, Skipped: 0
```

**Comment by andreaTP** [comment] 2024-12-12 13:22
Thanks for the report @mkarg , can you confirm you are working on latest `main`?
This issue should have been already solved [here](https://github.com/dylibso/chicory/commit/4da6c49719c3652a1b7bec2912b891a8000ed346).

Just tested and cannot reproduce on current `main`.

**Comment by mkarg** [comment] 2024-12-12 15:53
Tried it once more using a complete clean development setup: https://gitpod.io/#https://github.com/dylibso/chicory/. `mvn install` **will** fail there.

**Comment by andreaTP** [comment] 2024-12-12 17:25
First time using GitPod, but this is what it looks a plain `mvn clean install`:

![Screenshot from 2024-12-12 17-20-49](https://github.com/user-attachments/assets/ffc9f085-03b7-47fd-b641-96cb34418478)

The (automatically generated) `.gitpod.yml` contains the following:

```
# This configuration file was automatically generated by Gitpod.
# Please adjust to your needs (see https://www.gitpod.io/docs/introduction/learn-gitpod/gitpod-yaml)
# and commit this file to your remote git repository to share the goodness with others.

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart

tasks:
  - init: mvn install -DskipTests=false
```

Closing as it's not reproducible, feel free to re-open when there is a repro.

**Closed by andreaTP** 2024-12-12 17:25 UTC

**Comment by mkarg** [comment] 2024-12-13 12:40
Am 12.12.2024 um 18:25 schrieb Andrea Peruffo:
> mvn install -DskipTests=false

I don't know how you made that work, but each time I let Gitpod create a fresh environment for me, the result is always a build failure (and strange but true, always different ones).

Andrea, I have shared the running Gitpod workspace with you (see private mail), so feel free to look into it, it will serve a a reproducer.

Latest attempt looks like this:

```

[ERROR] Errors:
[ERROR]   FuzzTest.numericOnlyFuzz:60->generateTestData:30 » Runtime java.io.IOException: Cannot run program "wasm-tools" (in directory "."): error=2, No such file or directory
[ERROR]   FuzzTest.tableOnlyFuzz:77->generateTestData:30 » Runtime java.io.IOException: Cannot run program "wasm-tools" (in directory "."): error=2, No such file or directory
[INFO]
[ERROR] Tests run: 22, Failures: 0, Errors: 2, Skipped: 19
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Chicory 999-SNAPSHOT:
[INFO]
[INFO] Chicory ............................................ SUCCESS [  2.813 s]
[INFO] Chicory - WASM Corpus .............................. SUCCESS [  1.783 s]
[INFO] Chicory - WASM ..................................... SUCCESS [ 10.214 s]
[INFO] Chicory - Runtime .................................. SUCCESS [  3.248 s]
[INFO] Chicory - AOT - Experimental ....................... SUCCESS [  3.257 s]
[INFO] Chicory - AOT Maven Plugin - Experimental .......... SUCCESS [  2.334 s]
[INFO] Chicory - Log ...................................... SUCCESS [  1.504 s]
[INFO] Chicory - Host Module Annotations - Experimental ... SUCCESS [  1.534 s]
[INFO] Chicory - Host Module Annotation Processor - Experimental SUCCESS [  3.594 s]
[INFO] Chicory - WASI ..................................... SUCCESS [  2.264 s]
[INFO] Chicory - wabt ..................................... SUCCESS [  6.693 s]
[INFO] Chicory - Test Gen Maven Plugin .................... SUCCESS [  3.071 s]
[INFO] Chicory - AOT tests ................................ SUCCESS [ 51.808 s]
[INFO] Chicory - BOM ...................................... SUCCESS [  0.150 s]
[INFO] Chicory - Cli - Experimental ....................... SUCCESS [  2.317 s]
[INFO] Chicory - Docs Lib ................................. SUCCESS [  1.603 s]
[INFO] Chicory - Fuzz ..................................... FAILURE [  1.595 s]
[INFO] Chicory - Host Module - IT ......................... SKIPPED
[INFO] Chicory - JMH ...................................... SKIPPED
[INFO] Chicory - Machines tests ........................... SKIPPED
[INFO] Chicory - Runtime tests ............................ SKIPPED
[INFO] Chicory - WASI Test Gen Maven Plugin ............... SKIPPED
[INFO] Chicory - WASI Tests ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:40 min
[INFO] Finished at: 2024-12-13T12:31:57Z
[INFO] ------------------------------------------------------------------------

```

**Comment by andreaTP** [comment] 2024-12-13 13:22
Resolved offline.
